<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <?php
    include 'phplib/yandex.metrika.inc';
    include 'phplib/google.analytics.inc';
    ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="title" content="Регистрация в Дельту">
    <title>Регистрация в Дельту</title>
    <link href="CSS/common.css" rel="stylesheet" type="text/css">
    <link href="CSS/mycabinet.css" rel="stylesheet" type="text/css">
    <script src="JS/common.js"></script>
    <script src="JS/form_functions.js"></script>
    <script src="JS/lib/is.min.js"></script>
</head>

<body>
<div class="title">
    <h1>Регистрация в летний физико-математический лагерь "Дельта"</h1>
</div>
<div class="main">
    <br>
    <br>
    <br>
    <br>
    <br>
    Регистрация в летний лагерь 2020 года пока ещё не открыта.<br>
    Следите за новостями на нашей страничке в Facebook:
    <a href="https://www.facebook.com/Summer.Camp.Delta/" target="_blank">https://www.facebook.com/Summer.Camp.Delta/</a>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
</div>
</body>
</html>
