<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <?php
    // include 'phplib/yandex.metrika.inc';
    // include 'phplib/google.analytics.inc';
    ?>
    <title>&Delta;elta - летний физико-математический лагерь в Мюнхене</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Международный летний детский лагерь в Мюнхене. Отдых со смыслом: математика, физика, программирование. Сроки: 22 июля - 5 августа 2019 г. Стоимость: 850 Евро.">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="CSS/common.css" rel="stylesheet" type="text/css">
    <link href="CSS/index.css" rel="stylesheet" type="text/css">

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="JS/lib/masonry.pkgd.min.js"></script>
    <script src="JS/index.js"></script>
    <?php
    require_once 'phplib/dbConnect.php';
    require_once 'phplib/news.php';
    ?>
</head>


